title: The Sweetness Project
description: I am a curious human, data professional, and environmental writer. Welcome to my home base on the internet.
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
