remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
title: Mike Packard
description: I am a data professional, environmental writer, and curious human - and this is my home base on the internet.
